config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'gossip/:index', to: 'gossip#gossip', as: 'gossip'
  get '/team', to: 'team#index'
  get '/contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def gossip
    @gossip = Gossip.find(params[:index])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gossips = Gossip.all
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contact/index.html.erb
<p> Will be added <strong><em>soonTM</em></strong> <p>

app/views/gossip/gossip.html.erb
<h1>Gossip number <%= @gossip.id%></h1>
<p>Created on <%= @gossip.created_at%></p>
<p><%= @gossip.author%></p>
<p><%= @gossip.content%></p>

app/views/home/index.html.erb
<h1 class="card-title"><u>Welcome to the Gossip Project</u><br><br></h1>
<h2>Last freshly made gossips just for u : <br><br></h2>
<div class="card-columns">
  <% @gossips.each do |gossip| %>
    <div class="card p-2">
      <blockquote class="blockquote mb 1 card-body">
      <p><%= gossip.content%></p>
        <small class="text-muted">
        <%= link_to "#{gossip.author}", gossip_path(gossip.id) %>
        </small>
      </blockquote>
    </div>
  <% end%>
  <div class="card">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"     integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <body class="card text-center">
        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item">
      <%= link_to "Home", "/", class:"nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Team", "/team", class:"nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Contact", "/contact", class:"nav-link"%>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/team/index.html.erb
<h1>Team</h1>
<p>Raphael Caillaux @Raphael <em>(on slack)</em></p>